osx_image: xcode9.3
language: swift

before_install:
  - gem install xcpretty xcpretty-travis-formatter

branches:
  only:
    - master

script:
  - xcodebuild test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' -project ci-codecov-test.xcodeproj -scheme ci-codecov-test CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -f `xcpretty-travis-formatter`
  - xcodebuild test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.0' -project ci-codecov-test.xcodeproj -scheme ci-codecov-test CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -f `xcpretty-travis-formatter`

#  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)